### ISSUE TITLE
Installation Error on python 2.7.10

### ISSUE THREAD

**Issue by ikeikeikeike** [satoshi03/slack-python-webhook#1]
I used this package on the python 2.7.10(pyenv) and it defined that like this also.

```
$ cat requirements.txt
slackweb=1.0.5
```

After this I executed pip command.

```
$ ~/.pyenv/versions/myenv/bin/pip install -r requirements.txt

Exception:
Traceback (most recent call last):
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/basecommand.py", line 291, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/req/req_file.py", line 137, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
    reqs = list(parse_requirements(s))
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
    "version spec")
  File "/home/deploy/.pyenv/versions/2.7.10/envs/myenv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected version spec in slackweb=1.0.5 at =1.0.5
```

How do we fix that ?

**Comment by RealOrangeOne** [comment]
If you read the error, it states a parse error in your `requirements.txt` file. To define a requirement in the `requirements.txt` file, you need to use a double equals to specify the version.
Your file should read `slackweb==1.0.5`.

**Comment by ikeikeikeike** [comment]
I already fixed that before. Thank you for your explaining.

**Comment by satoshi03** [comment]
Thank you! @RealOrangeOne
As he said, please check your requirements.txt.
